spring:
  application:
    name: camel-servlet
server:
  port: 8080
camel:
  springboot:
    auto-startup: true
  component:
    servlet:
      mapping:
        context-path: /camel/*
        servlet-name: CamelServlet