spring:
  application:
    name: camel-application
server:
  port: 8088
cxf:
  path: /
service1:
  path: /MyService1/BookService
service2:
  path: /MyService2/BookService
userservcie:
  path: /MyService3/UserService