spring:
  application:
    name: camel-application
server:
  port: 8088
camel:
  component:
    rest-api:
      enabled: true
  springboot:
    name: camel-rest
cxf:
  path: /
service1:
  path: /MyService1/BookService
service2:
  path: /MyService2/BookService